#!/bin/bash
echo "Please enter mysql login"
read login
echo "Please enter mysql password"
read password
mysql -u$login -p$password < dump.mysql
sed -i -e "s/root/"$login"/" src/main/resources/mybatis/dbconfig.properties
sed -i -e "s/password/"$password"/" src/main/resources/mybatis/dbconfig.properties
mvn jetty:run
